apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ovoweb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv-ovoweb/